BUILTIN_REPOS = {
    "abap",
    "apex",
    "azureresourcemanager",
    "c",
    "cloudformation",
    "cobol",
    "cpp",
    "csharpsquid",
    "css",
    "docker",
    "dart",
    "external_android-lint",
    "external_bandit",
    "external_cfn-lint",
    "external_checkstyle",
    "external_detekt",
    "external_eslint_repo",
    "external_fbcontrib",
    "external_findsecbugs",
    "external_flake8",
    "external_golint",
    "external_govet",
    "external_hadolint",
    "external_ktlint",
    "external_mypy",
    "external_phpstan",
    "external_pmd",
    "external_pmd_apex",
    "external_psalm",
    "external_pylint",
    "external_rubocop",
    "external_ruff",
    "external_scalastyle",
    "external_scapegoat",
    "external_spotbugs",
    "external_stylelint",
    "external_swiftlint",
    "external_tflint",
    "external_tslint_repo",
    "external_valgrind-c",
    "external_valgrind-cpp",
    "external_valgrind-objc",
    "ipython",
    "flex",
    "go",
    "java",
    "javabugs",
    "javascript",
    "javasecurity",
    "jcl",
    "jssecurity",
    "kotlin",
    "kubernetes",
    "objc",
    "php",
    "phpsecurity",
    "pli",
    "plsql",
    "python",
    "pythonbugs",
    "pythonsecurity",
    "roslyn.sonaranalyzer.security.cs",
    "rpg",
    "ruby",
    "scala",
    "secrets",
    "swift",
    "terraform",
    "text",
    "tsql",
    "tssecurity",
    "typescript",
    "vb",
    "vbnet",
    "Web",
    "xml"
}

REPORT_TASKS = [
    'getBranches',
    'getProjectPullRequests',
    'getRules',
    'getProfileRules',
    'getProjectAnalyses',
    'getProjectDetails',
    'getApplicationDetails',
    'getServerInfo',
    'getProjectBindings',
    'getGates',
    'getPlugins',
    'getDefaultTemplates',
    'getTemplates',
    'getPlugins',
    'getPortfolioDetails',
    'getPortfolioProjects',
    'getProfiles',
    'getProjectSettings',
    'getUsers',
    'getUsage'
]

MIGRATION_TASKS = [
    'getProfileUsers',
    'getApplications',
    'getPortfolioProjects',
    'getAcceptedIssues',
    'getSafeHotspots',
    'getTemplateUsersViewers',
    'getDefaultTemplates',
    'getProjects',
    'getProjectUsersViewers',
    'getUsers',
    'getProjectGroupsScanners',
    'getProjectPullRequests',
    'getServerSettings',
    'getRules',
    'getTemplateGroupsScanners',
    'getPortfolios',
    'getActiveProfileRules',
    'getGateUsers',
    'getProjectWebhookDeliveries',
    'getNewCodePeriods',
    "getProjectGroupsPermissions",
    'getProjectUsersScanners', "getProjectTags",
    'getProjectTasks', 'getRuleDetails', "getProfileBackups",
    'getUserGroups', 'getProjectSettings', 'getTemplateUsersScanners', 'getServerWebhooks',
    'getProjectGroupsViewers', 'getTemplateGroupsViewers', 'getUsage', 'getPluginRules',
    'getApplicationDetails', 'getProjectDetails', 'getProjectTemplateIssues', 'getBranches',
    'getGateGroups', 'getDeactivatedProfileRules', 'getBindings', 'getProjectWebhooks', 'getWebhooks',
    'getProjectIssues', 'getProfiles', 'getProjectBindings', 'getProfileGroups', 'getFixedHotspots',
    'getLabeledIssues', 'getProjectAnalyses', 'getGroups', 'getTemplateRules', 'getPluginIssues',
    'getGateConditions', 'getPlugins', 'getWebhookDeliveries', 'getPortfolioDetails', 'getGates',
    'getUserTokens', 'getProjectPluginIssues', 'getFalsePositiveIssues', 'getRepos', 'getTemplates',
    'getServerInfo']

PLUGINS = [{'key': 'abap', 'updatedAt': 1735825865547}, {'key': 'sonarapex', 'updatedAt': 1751447712751},
           {'key': 'architecture', 'updatedAt': 1756314428479},
           {'key': 'architecturejavascriptfrontend', 'updatedAt': 1756314428479},
           {'key': 'architecturejavafrontend', 'updatedAt': 1756314428479},
           {'key': 'csharpenterprise', 'updatedAt': 1753353825790}, {'key': 'cpp', 'updatedAt': 1755546153102},
           {'key': 'cobol', 'updatedAt': 1741620583759}, {'key': 'dart', 'updatedAt': 1751284202496},
           {'key': 'dbd', 'updatedAt': 1756283844558}, {'key': 'dbdjavafrontend', 'updatedAt': 1756283844558},
           {'key': 'dbdpythonfrontend', 'updatedAt': 1756283844558}, {'key': 'flex', 'updatedAt': 1732614148938},
           {'key': 'go', 'updatedAt': 1756120177908}, {'key': 'web', 'updatedAt': 1740589757791},
           {'key': 'iac', 'updatedAt': 1755505503817}, {'key': 'iacenterprise', 'updatedAt': 1755505503817},
           {'key': 'jcl', 'updatedAt': 1741615095382}, {'key': 'jacoco', 'updatedAt': 1674638756383},
           {'key': 'javasymbolicexecution', 'updatedAt': 1752481487675}, {'key': 'java', 'updatedAt': 1753353825790},
           {'key': 'javascript', 'updatedAt': 1756314428479}, {'key': 'kotlin', 'updatedAt': 1752494806603},
           {'key': 'php', 'updatedAt': 1756214186249}, {'key': 'pli', 'updatedAt': 1734534749088},
           {'key': 'plsql', 'updatedAt': 1753353825790}, {'key': 'python', 'updatedAt': 1757001742140},
           {'key': 'rpg', 'updatedAt': 1734586186837}, {'key': 'ruby', 'updatedAt': 1746605377201},
           {'key': 'rust', 'updatedAt': 1756223735727}, {'key': 'sonarscala', 'updatedAt': 1747047637834},
           {'key': 'jasmin', 'updatedAt': 1757326981075}, {'key': 'swift', 'updatedAt': 1751879681182},
           {'key': 'tsql', 'updatedAt': 1753353825790}, {'key': 'textenterprise', 'updatedAt': 1757416679234},
           {'key': 'vbnetenterprise', 'updatedAt': 1753353825790}, {'key': 'vb', 'updatedAt': 1748262751905},
           {'key': 'security', 'updatedAt': 1756204001284},
           {'key': 'securitycsharpfrontend', 'updatedAt': 1756204001284},
           {'key': 'securitygofrontend', 'updatedAt': 1756204001284},
           {'key': 'securityjsfrontend', 'updatedAt': 1756204001284},
           {'key': 'securityjavafrontend', 'updatedAt': 1756204001284},
           {'key': 'securitykotlinfrontend', 'updatedAt': 1756204001284},
           {'key': 'securityphpfrontend', 'updatedAt': 1756204001284},
           {'key': 'securitypythonfrontend', 'updatedAt': 1756204001284},
           {'key': 'securityvbnetfrontend', 'updatedAt': 1756204001284}, {'key': 'xml', 'updatedAt': 1744024174680}]
SEVERITY_MAPPING = {
    "INFO": "INFO",
    "LOW": "INFO",
    "MINOR": "MINOR",
    "MEDIUM": "MINOR",
    "HIGH": "MAJOR",
    "MAJOR": "MAJOR",
    "CRITICAL": "CRITICAL",
    "BLOCKER": "BLOCKER",
}
